[functions.verify-google-play-purchase]
verify_jwt = false

[functions.seedream-proxy]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false

[functions.merge-anon-credits]
verify_jwt = true

[functions.paypal-webhook]
verify_jwt = false
