import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { COLORS, TYPOGRAPHY } from '../../constants';

const TermsOfServiceScreen: React.FC = () => {
  return (
    <SafeAreaView style={styles.safeArea}>
      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <View style={styles.header}>
          <Text style={styles.title}>Terms of Service</Text>
          <Text style={styles.meta}>Effective Date: January 19, 2026</Text>
          <Text style={styles.meta}>Last Updated: January 19, 2026</Text>
        </View>

        <Text style={styles.heading}>1. Acceptance of Terms</Text>
        <Text style={styles.paragraph}>
          Welcome to Miri ("we," "us," or "our"), operated by Foshan Xinghang Trading Co., Ltd.
        </Text>
        <Text style={styles.paragraph}>
          These Terms of Service ("Terms") govern your access to and use of the Miri mobile application, website, and any
          related AI-powered features, content generation tools, and platforms provided by us (collectively, the
          "Services").
        </Text>
        <Text style={styles.paragraph}>
          By creating an account, accessing, or using the Services, you confirm that you have read, understood, and
          agreed to be bound by these Terms. If you do not agree, you must immediately stop using the Services.
        </Text>

        <Text style={styles.heading}>2. Changes to Services and Terms</Text>
        <Text style={styles.subheading}>2.1 Future Functionality</Text>
        <Text style={styles.paragraph}>
          You acknowledge that the Services are evolving. We reserve the right to modify, update, suspend, or discontinue
          any part of the Services (including adding new AI features, changing algorithms, or introducing paid tiers) at
          any time without prior notice. These Terms apply to all current and future features of Miri, unless we provide a
          separate agreement for a specific new feature.
        </Text>
        <Text style={styles.subheading}>2.2 Updates to Terms</Text>
        <Text style={styles.paragraph}>
          We may update these Terms from time to time. If we make material changes, we will notify you within the App.
          Your continued use of the Services after such changes constitutes your acceptance of the new Terms.
        </Text>

        <Text style={styles.heading}>3. Your Access and Use</Text>
        <Text style={styles.subheading}>3.1 Age Requirement</Text>
        <Text style={styles.paragraph}>
          The Services are intended for users who are at least 13 years old (or the minimum age required in your
          jurisdiction). If you are under 18, you represent that you have your parent or guardian's permission to use the
          Services.
        </Text>
        <Text style={styles.subheading}>3.2 License to You</Text>
        <Text style={styles.paragraph}>
          Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable,
          non-sublicensable, revocable license to access and use the Services for your personal, non-commercial use.
        </Text>

        <Text style={styles.heading}>4. Input and Output (AI Content)</Text>
        <Text style={styles.subheading}>4.1 Definitions</Text>
        <Text style={styles.paragraph}>
          "Input": Any text, images, photos, videos, audio, or other data you upload, type, or submit to the Services.
        </Text>
        <Text style={styles.paragraph}>
          "Output": Any images, text, modifications, or content generated by the Services based on your Input.
        </Text>
        <Text style={styles.subheading}>4.2 Ownership of Input</Text>
        <Text style={styles.paragraph}>
          You retain all rights and ownership of your Input. You represent and warrant that you own or have the necessary
          licenses to submit the Input and that it does not violate any third-party rights.
        </Text>
        <Text style={styles.subheading}>4.3 License to Us</Text>
        <Text style={styles.paragraph}>
          By using the Services, you grant us and our third-party providers (such as BytePlus, AWS, Google Cloud) a
          worldwide, non-exclusive, royalty-free, transferable license to use, reproduce, process, modify, and display
          your Input and Output solely for the purposes of:
        </Text>
        <Text style={styles.list}>
          - Providing and maintaining the Services;{'\n'}
          - Debugging and fixing technical issues;{'\n'}
          - Complying with applicable laws. (Note: Our use of your data is further limited by our Privacy Policy, which
          dictates strict ephemeral processing for biometric data.)
        </Text>
        <Text style={styles.subheading}>4.4 Nature of AI Output</Text>
        <Text style={styles.paragraph}>You acknowledge that due to the nature of Artificial Intelligence:</Text>
        <Text style={styles.list}>
          - Output may not be unique and similar results may be generated for other users.{'\n'}
          - Output may be inaccurate, offensive, or physically impossible. We make no warranties regarding the realism,
          accuracy, or quality of the Output.{'\n'}
          - You are responsible for evaluating the Output before using it.
        </Text>

        <Text style={styles.heading}>5. Prohibited Conduct</Text>
        <Text style={styles.paragraph}>You agree NOT to use the Services to:</Text>
        <Text style={styles.list}>
          - Illegal Use: Violate any applicable laws or regulations.{'\n'}
          - Harmful Content: Generate or upload content that is defamatory, obscene, pornographic, or promotes
          violence/hate speech.{'\n'}
          - Deepfakes/Deception: Create content intended to deceive others, impersonate individuals, or spread
          misinformation.{'\n'}
          - Reverse Engineering: Attempt to extract source code, algorithms, models, or parameters from the Services.{'\n'}
          - Automated Access: Use bots, scrapers, or automated tools to access the Services.{'\n'}
          - Interference: Disrupt the integrity or performance of the Services or third-party data contained therein.
        </Text>

        <Text style={styles.heading}>6. DISCLAIMER: NO MEDICAL ADVICE</Text>
        <Text style={styles.paragraph}>
          THE SERVICES ARE FOR ENTERTAINMENT AND ARTISTIC PURPOSES ONLY.
        </Text>
        <Text style={styles.paragraph}>
          No Professional Advice: The Services (including any "reshaping," "liquify," or "AI generation" features) do NOT
          constitute medical, surgical, or aesthetic advice.
        </Text>
        <Text style={styles.paragraph}>
          Simulation Only: Any changes to facial features or body shapes generated by the App are artistic simulations
          and DO NOT represent achievable biological results.
        </Text>
        <Text style={styles.paragraph}>
          No Reliance: You agree not to rely on the Output for making decisions regarding plastic surgery, medical
          treatments, or health. We expressly disclaim all liability for any medical procedures you undertake based on the
          App's content.
        </Text>

        <Text style={styles.heading}>7. Intellectual Property</Text>
        <Text style={styles.subheading}>7.1 Our Rights</Text>
        <Text style={styles.paragraph}>
          The Services, including the interface, software code, AI models, logos, and branding, are the exclusive
          property of Foshan Xinghang Trading Co., Ltd. and its licensors.
        </Text>
        <Text style={styles.subheading}>7.2 Third-Party Services</Text>
        <Text style={styles.paragraph}>
          The Services may integrate with third-party models or APIs (e.g., Seedream/BytePlus). You acknowledge that your
          use of such features is subject to the terms of those third parties.
        </Text>

        <Text style={styles.heading}>8. Fees, Points, and Subscriptions</Text>
        <Text style={styles.subheading}>8.1 Free Services</Text>
        <Text style={styles.paragraph}>
          We offer a basic version of the App that allows you to use certain features free of charge ("Free Services").
          The Free Services may include advertisements, watermarks, and limitations on usage or resolution.
        </Text>
        <Text style={styles.subheading}>8.2 Points / Credits (Pay-Per-Use)</Text>
        <Text style={styles.paragraph}>Our AI generation features primarily operate on a credit-based system.</Text>
        <Text style={styles.paragraph}>
          Purchase: You may purchase "Points," "Credits," or "Tokens" (collectively, "Virtual Items") through the App
          Store or Google Play to unlock AI generation tasks.
        </Text>
        <Text style={styles.paragraph}>
          Consumption: Points are consumed per generation request. The cost per task may vary depending on the complexity
          of the feature.
        </Text>
        <Text style={styles.paragraph}>
          Non-Refundable: Unless required by law, Points are non-refundable and constitute a non-transferable license to
          use the Services.
        </Text>
        <Text style={styles.subheading}>8.3 Subscriptions (Optional/Future)</Text>
        <Text style={styles.paragraph}>
          We may, at our discretion, offer subscription plans ("Miri Pro") that provide access to specific premium
          features (e.g., watermark removal, high-definition export, or discounted Point bundles).
        </Text>
        <Text style={styles.paragraph}>
          Limitations: Subscriptions do NOT include unlimited AI generations. AI generation may still require the
          consumption of Points, even for subscribers.
        </Text>
        <Text style={styles.paragraph}>
          Auto-Renewal: If offered, subscriptions will automatically renew at the end of each billing period unless
          canceled at least 24 hours before the current period ends via your Account Settings.
        </Text>
        <Text style={styles.subheading}>8.4 No Refunds</Text>
        <Text style={styles.paragraph}>
          All purchases made through the App Store or Google Play (including Points and Subscriptions) are final and
          non-refundable, except as required by applicable law or the store's specific refund policy. Please contact
          Apple or Google directly for any refund requests.
        </Text>

        <Text style={styles.heading}>9. Indemnification</Text>
        <Text style={styles.paragraph}>
          You agree to indemnify, defend, and hold harmless us, our affiliates, and our officers from any claims,
          liabilities, damages, and expenses (including legal fees) arising from:
        </Text>
        <Text style={styles.list}>
          - Your use of the Services;{'\n'}
          - Your violation of these Terms;{'\n'}
          - Your Input or the Output generated from it;{'\n'}
          - Any reliance you place on the Services for medical or surgical decisions.
        </Text>

        <Text style={styles.heading}>10. Limitation of Liability</Text>
        <Text style={styles.paragraph}>
          TO THE FULLEST EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
          CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS OR DATA. OUR TOTAL LIABILITY FOR ANY CLAIM ARISING
          OUT OF THESE TERMS SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE PAST 12 MONTHS, OR $50 USD, WHICHEVER IS
          GREATER.
        </Text>

        <Text style={styles.heading}>11. Governing Law and Dispute Resolution</Text>
        <Text style={styles.subheading}>11.1 Governing Law</Text>
        <Text style={styles.paragraph}>These Terms are governed by the laws of the People's Republic of China.</Text>
        <Text style={styles.subheading}>11.2 Jurisdiction</Text>
        <Text style={styles.paragraph}>
          Any dispute arising out of these Terms shall be submitted to the exclusive jurisdiction of the competent court
          in Chancheng District, Foshan City, Guangdong Province, China.
        </Text>

        <Text style={styles.heading}>12. Contact Us</Text>
        <Text style={styles.paragraph}>If you have questions about these Terms, please contact:</Text>
        <Text style={styles.paragraph}>Email: support@miriai.app</Text>
        <Text style={styles.paragraph}>Company: Foshan Xinghang Trading Co., Ltd.</Text>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
  },
  content: {
    padding: 20,
    gap: 12,
  },
  header: {
    gap: 6,
  },
  title: {
    fontSize: TYPOGRAPHY.FONT_SIZE_XL,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_BOLD,
    color: COLORS.TEXT_PRIMARY,
  },
  meta: {
    fontSize: TYPOGRAPHY.FONT_SIZE_SM,
    color: COLORS.TEXT_SECONDARY,
  },
  heading: {
    fontSize: TYPOGRAPHY.FONT_SIZE_LG,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_SEMIBOLD,
    color: COLORS.TEXT_PRIMARY,
    marginTop: 8,
  },
  subheading: {
    fontSize: TYPOGRAPHY.FONT_SIZE_MD,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_SEMIBOLD,
    color: COLORS.TEXT_PRIMARY,
    marginTop: 4,
  },
  paragraph: {
    fontSize: TYPOGRAPHY.FONT_SIZE_SM,
    color: COLORS.TEXT_SECONDARY,
    lineHeight: 20,
  },
  list: {
    fontSize: TYPOGRAPHY.FONT_SIZE_SM,
    color: COLORS.TEXT_SECONDARY,
    lineHeight: 20,
  },
});

export default TermsOfServiceScreen;
